### ISSUE TITLE
typo in the wiki "hello world"

### ISSUE THREAD

**Issue by mmueller-xyz** [AlexandreRouma/DankBot#16]
The discription of the `helloworld` command says 
> Say 'Hellow World' !

 insetead of 
>  Say 'Hello World' !

**Comment by AlexandreRouma** [comment]
It seems like you have an old version of dankbot, I remember fixing that a couple weeks agao ^^
Thanks for reporting though !

**Comment by mmueller-xyz** [comment]
the github wiki has the typo
